name: Junit test and Checkstyle

on: 
  workflow_call:
   secrets:
     tokens:
       required: true
   

permissions:
  contents: write
  checks: write
  id-token: write
  
  
jobs:
  buildAndTest:

    runs-on: ubuntu-latest
    timeout-minutes: 3

    # ##########################
    # # CHANGE THESE VARIABLES #
    # ##########################
    


    env:
      #tests jar file path
      Junit_Test_Jar_File: lab1.jar
      #the class that has the tests
      Junit_Class_To_run: lab1.CSCD211Lab1Tests
      #the date to auto fail (if today >= deadline then fail)
      # NOTE: need .autotests/jar/deadLine.jar
      #Dead_Line: 12-05-2022

    
    steps:
      - name: Geting the github project
        uses: actions/checkout@v3

      - name: Getting our tools and tests
        uses: actions/checkout@v3
        with:
 #         token: ${{ secrets.access-token }}
          repository: lthomas32/CSCD_TEST
          path: 'tools'
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          

 
          

      - name: Get Junit Launcher
        run: wget https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.9.2/junit-platform-console-standalone-1.9.2.jar
      #Used to have the Junit test separate from the project




#      - name: Getting All The test Jar
 #       run: wget -O lab1.jar https://github.com/lthomas32/CSCD211_Test/blob/main/${{ env.Junit_Test_Jar_Repo_path}}${{ env.Junit_Test_Jar_File }}?raw=true

#      - name: Getting deadline tool
#        run: wget https://github.com/EWU-CSCD212/cscd212-f22-jar-tests-files/raw/master/tools/deadLine.jar
      - name: Build Code for testing
        run: javac -Xlint:unchecked -d out/classes $(find src -name '*.java')
      - name: Run junit test (${{ env.Junit_Class_To_run }})
        run: java -jar junit-platform-console-standalone-1.9.2.jar --reports-dir=build/test-results/test1 -cp tools/${{ env.Junit_Test_Jar_File }} -cp out/classes --select-class=${{ env.Junit_Class_To_run }}
        

      # Test deadline
      # - name: check deadline
      #   if: always()
      #   run: java -jar tools/tools/deadLine.jar ${{ env.Dead_Line }}
      
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/test*/TEST*.xml'
